name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: 
          - macOS-latest
          - ubuntu-latest
          - windows-latest 
        node-version: 
          - 8
          - 10
          - 12
    runs-on: ${{matrix.os}} 
    
    steps:      
      # checkout the repos
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}      
      
      # install dependencies, build, and test
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present                   
      
      # run cf push
      - name: run cf
        run:  |           
          cf install-plugin -r CF-Community "cfdev" -f
          cf login -u ${{ secrets.cf_username }} -p ${{ secrets.cf_password }} -a ${{ secrets.cf_url }} --skip-ssl-validation -o Simran-trial -s development 
          cf push cf-sample-app -b https://github.com/cloudfoundry/nodejs-buildpack
